const COUNTRY_TO_CODE: Record<string, string> = {
  "usa": "us", "united states": "us", "united states of america": "us", "us": "us",
  "uk": "gb", "united kingdom": "gb", "great britain": "gb", "england": "gb",
  "germany": "de", "deutschland": "de",
  "netherlands": "nl", "holland": "nl",
  "france": "fr",
  "spain": "es", "españa": "es",
  "sweden": "se", "sverige": "se",
  "denmark": "dk", "danmark": "dk",
  "norway": "no", "norge": "no",
  "finland": "fi", "suomi": "fi",
  "canada": "ca",
  "australia": "au",
  "turkey": "tr", "türkkiye": "tr",
  "india": "in",
  "japan": "jp",
  "south korea": "kr", "korea": "kr",
  "brazil": "br", "brasil": "br",
  "singapore": "sg",
  "hong kong": "hk",
  "ireland": "ie",
  "italy": "it", "italia": "it",
  "portugal": "pt",
  "poland": "pl", "polska": "pl",
  "czech republic": "cs", "czechia": "cz", "česko": "cz",
  "switzerland": "ch", "schweiz": "ch",
  "austria": "at", "österreich": "at",
  "belgium": "be", "belgique": "be",
  "romania": "ro", "românia": "ro",
  "bulgaria": "bg",
  "hungary": "hu", "magyarország": "hu",
  "ukraine": "ua",
  "russia": "ru", "russian federation": "ru",
  "china": "cn",
  "israel": "il",
  "south africa": "za",
  "mexico": "mx", "méxico": "mx",
  "argentina": "ar",
  "chile": "cl",
  "colombia": "co",
  "thailand": "th", "ประเทศไทย": "th",
  "vietnam": "vn",
  "indonesia": "id",
  "malaysia": "my",
  "philippines": "ph",
  "new zealand": "nz",
  "estonia": "ee",
  "latvia": "lv",
  "lithuania": "lt",
  "luxembourg": "lu",
  "croatia": "hr",
  "slovenia": "si",
  "slovakia": "sk",
  "serbia": "rs",
  "greece": "gr",
  "cyprus": "cy",
  "malta": "mt",
  "iceland": "is",
  "liechtenstein": "li",
  "monaco": "mc",
  "andorra": "ad",
  "san marino": "sm",
  "panama": "pa",
  "costa rica": "cr",
  "peru": "pe",
  "uruguay": "uy",
  "paraguay": "py",
  "bolivia": "bo",
  "ecuador": "ec",
  "venezuela": "ve",
  "dominican republic": "do",
  "cuba": "cu",
  "jamaica": "jm",
  "trinidad and tobago": "tt",
  "barbados": "bb",
  "fiji": "fj",
  "papua new guinea": "pg",
  "pakistan": "pk",
  "bangladesh": "bd",
  "sri lanka": "lk",
  "nepal": "np",
  "myanmar": "mm",
  "cambodia": "kh",
  "laos": "la",
  "mongolia": "mn",
  "kazakhstan": "kz",
  "uzbekistan": "uz",
  "georgia": "ge",
  "armenia": "am",
  "azerbaijan": "az",
  "belarus": "by",
  "moldova": "md",
  "north macedonia": "mk",
  "albania": "al",
  "bosnia and herzegovina": "ba",
  "montenegro": "me",
  "kosovo": "xk",
  "morocco": "ma",
  "egypt": "eg",
  "tunisia": "tn",
  "algeria": "dz",
  "nigeria": "ng",
  "kenya": "ke",
  "ethiopia": "et",
  "ghana": "gh",
  "tanzania": "tz",
  "uganda": "ug",
  "senegal": "sn",
  "cameroon": "cm",
  "ivory coast": "ci", "côte d'ivoire": "ci",
  "congo": "cd",
  "zimbabwe": "zw",
  "zambia": "zm",
  "botswana": "bw",
  "namibia": "na",
  "mauritius": "mu",
  "madagascar": "mg",
  "mozambique": "mz",
  "angola": "ao",
  "lebanon": "lb",
  "jordan": "jo",
  "iraq": "iq",
  "iran": "ir",
  "saudi arabia": "sa",
  "uae": "ae", "united arab emirates": "ae", "dubai": "ae",
  "qatar": "qa",
  "kuwait": "kw",
  "bahrain": "bh",
  "oman": "om",
  "yemen": "ye",
  "syria": "sy",
  "palestine": "ps",
  "taiwan": "tw",
  "macau": "mo", "macao": "mo",
  "brunei": "bn",
  "east timor": "tl",
  "turkmenistan": "tm",
  "tajikistan": "tj",
  "kyrgyzstan": "kg",
  "afghanistan": "af",
  "libya": "ly",
  "sudan": "sd",
  "south sudan": "ss",
  "somalia": "so",
  "rwanda": "rw",
  "burundi": "bi",
  "malawi": "mw",
  "lesotho": "ls",
  "eswatini": "sz", "swaziland": "sz",
  "republic of the congo": "cg",
  "gabon": "ga",
  "equatorial guinea": "gq",
  "sao tome and principe": "st",
  "cape verde": "cv",
  "guinea-bissau": "gw",
  "gambia": "gm",
  "sierra leone": "sl",
  "liberia": "lr",
  "togo": "tg",
  "benin": "bj",
  "burkina faso": "bf",
  "niger": "ne",
  "mali": "ml",
  "chad": "td",
  "central african republic": "cf",
  "eritrea": "er",
  "djibouti": "dj",
  "comoros": "km",
  "seychelles": "sc",
  "tonga": "to",
  "samoa": "ws",
  "vanuatu": "vu",
  "solomon islands": "sb",
  "palau": "pw",
  "guam": "gu",
  "puerto rico": "pr",
  "us virgin islands": "vi",
  "bermuda": "bm",
  "cayman islands": "ky",
  "british virgin islands": "vg",
  "aruba": "aw",
  "curacao": "cw",
  "sint maarten": "sx",
  "bonaire": "bq",
  "turks and caicos": "tc",
  "montserrat": "ms",
  "anguilla": "ai",
  "saint lucia": "lc",
  "saint vincent": "vc",
  "grenada": "gd",
  "antigua and barbuda": "ag",
  "saint kitts and nevis": "kn",
  "dominica": "dm",
  "haiti": "ht",
};

function extractDomain(website: string | null): string | null {
  if (!website) return null;
  try {
    let url = website.trim();
    if (!url.startsWith("http")) url = "https://" + url;
    const hostname = new URL(url).hostname;
    return hostname.replace(/^www\./, "");
  } catch {
    return null;
  }
}

export function getProviderLogoUrl(website: string | null): string | null {
  const domain = extractDomain(website);
  if (!domain) return null;
  return `https://logo.clearbit.com/${domain}`;
}

export function getProviderFaviconUrl(website: string | null, size = 64): string | null {
  const domain = extractDomain(website);
  if (!domain) return null;
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=${size}`;
}

export function getCountryFlagUrl(country: string | null): string | null {
  if (!country) return null;
  const code = COUNTRY_TO_CODE[country.toLowerCase().trim()];
  if (!code) return null;
  return `https://flagcdn.com/24x18/${code}.png`;
}

export function getCountryFlagCode(country: string | null): string | null {
  if (!country) return null;
  return COUNTRY_TO_CODE[country.toLowerCase().trim()] || null;
}
